### ISSUE TITLE
TypeError: Subscripted generics cannot be used with class and instance checks

### ISSUE THREAD

**Issue by jpilaul** [google-research/jaxpruner#3]
I am using python3.9 and I am getting the following unit test error when installing:

```
Traceback (most recent call last):
  File "/home/jpilault/jaxpruner/jaxpruner/sparsity_distributions_test.py", line 63, in testUniformSparsityMapGeneratorWithCustomMap
    result = sparsity_distributions.uniform(
  File "/home/jpilault/jaxpruner/jaxpruner/sparsity_distributions.py", line 72, in uniform
    if isinstance(params, chex.Array):
  File "/usr/lib/python3.9/typing.py", line 703, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/usr/lib/python3.9/typing.py", line 706, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

**Comment by evcu** [comment]
Upgrading to python 3.11 should solve this (another commit fixing the another error for python 3.11 is on its way.) will update it here.

**Comment by evcu** [comment]
d92a781 fixes this. It should now work with latest python (3.11).
